name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Makkan NestJS App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

    - name: SSH and deploy
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          cd ~/Makkan-nest
          git pull origin main
          npm install
          npm run build
          pm2 restart Makkan-nest
        EOF
